apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: event-simulator-pod
  name: event-simulator-pod
spec:
  containers:
  - image: kodekloud/event-simulator
    name: event-simulator-pod
  - image: some-image-processor
    name: image-processor
