apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-Demo-Cluster
  region: us-east-1

vpc:
  id: vpc-05aa8087b3d14180b
  cidr: "192.168.0.0/16"
  subnets:
    public:
      us-east-1a:
        id: subnet-0f134900eb447dcb4
      us-east-1b:
        id: subnet-06e383789fd3e52da
    private:
      us-east-1a:
        id: subnet-0ba006dfbfa3ec427
      us-east-1b:
        id: subnet-0687c345a4a904944

nodeGroups:
  - name: EKS-public-workers
    instanceType: t2.medium
    desiredCapacity: 2
  - name: EKS-private-workers
    instanceType: t2.medium
    desiredCapacity: 1
    privateNetworking: true